### ISSUE TITLE
Handle late drop-outs from pickups

### ISSUE THREAD

**Issue by tiltec** [karrot-dev/karrot-frontend#1108]
Currently, users can drop out from joined pickups at any time. This causes problems when no replacement person can be found (then all the tasty food goes to waste). It's especially problematic when dropping out late, e.g. less then 24 hours before the pickup will take place.

I recently heard about this problem from the "Foodsharing i Östersund" group, and they had the idea to display a group-defined message if people drop out late. In this message, they want to show what you should do if you have to drop out.

In addition to that, I could imagine creating extra email and push notifications in this case:
- the pickup is upcoming and
- all people dropped out recently and
- nobody joined again within 1 hour after the last person dropped out

Maybe I should create a post about this in the community forum and gather some feedback.

**Comment by djahnie** [comment]
That means we'd need the following:
- a new field in the GroupEdit form to specify the message
- a popup that displays said message when someone drops out late
- a new mail and push notification as specified above

Sounds good to me!
I like the 24 hour threshold, too. Same as in foodsharing.de. I think I would also add a default message in case the group didn't insert one yet – just like with the application questions. The other possibility would be to just not have the pop-up if the group didn't compose a message, but I think having late drop-outs is one of the most annoying things for a foodsaving group and it should be made clear to the people doing it, that it's better to be avoided...

**Comment by tiltec** [comment]
Opened a forum thread about this: https://community.foodsaving.world/t/how-do-you-handle-late-drop-outs-from-pickups/213

**Comment by djahnie** [comment]
The forum post shows that this also touched the topic of #986 so it might need more discussion and/or just waiting for store walls to be there before starting to implement things.

**Comment by tiltec** [comment]
There was some discussion in https://community.foodsaving.world/t/how-do-you-handle-late-drop-outs-from-pickups/213 and one concrete proposal emerged: [**show user pickup statistics**](https://community.foodsaving.world/t/how-do-you-handle-late-drop-outs-from-pickups/213/11)

From my point of view, it might also be helpful to show a group/store-specific warning when dropping out less then 24h before.

**Comment by tiltec** [comment]
We could also show the pickup history in the detail sidebar, to make it easier to find out who recently dropped out.

**Comment by nicksellen** [comment]
We implemented one of the suggestions for this, from the community forum thread, in this PR https://github.com/yunity/karrot-frontend/pull/2163

It looks like this:

![](https://user-images.githubusercontent.com/31616/90952221-26f8f800-e462-11ea-9e17-fd6e7a48221b.png)

**Comment by nicksellen** [comment]
I think it's possible to extract something else to develop out of this, even if it doesn't address all points.

e.g. It could still be nice to notify people who have it marked as a favourite place...

**Comment by nicksellen** [comment]
Moved to codeberg https://codeberg.org/karrot/karrot-frontend/issues/1108
