### ISSUE TITLE
Improve notifications when somebody left the group

### ISSUE THREAD

**Issue by tiltec** [karrot-dev/karrot-frontend#1619]
From Sylvia, EfA:

> Gibt es die Möglichkeit, dass auch der Austritt eines Nutzers, z.B. aus unserer EfA-Gruppe angezeigt wird.
> Ich wollte gerade nachsehen, wieviele Helfer bei EfA in Karrot eingetragen sind und stelle fest, dass es weniger sind. Jetzt suche ich herum, wer sich abgemeldet hat.

There's a history entry, but it has some limitations:
- history UI doesn't have filters yet
- entry payload contains only the user id, not name or profile picture

As the profile is not visible anymore to members, it usually shows as "?" - not very helpful.
This should be improved.

Additionally, it could be helpful if there was a bell notification when a user is leaving the group.

**Comment by dwaxweiler** [comment]
I agree that it is hard to trace who has left the group. While I do not know about the technical implementation of the history, I wonder whether only the (first) name of the user who has left could stay in the log. After 2 or more weeks, it could also be removed.

By the way, what does "EfA" stand for?

**Comment by tiltec** [comment]
I like the concept of a "grace period" for the names to be visible. From a technical perspective, that's more work - currently it's rather easy: members can only see names and profiles of other members. If someone leaves the group, those data becomes unavailable and only the user id is left. In these cases we show `?`.

EfA is a group on karrot.world: https://karrot.world/#/groupPreview/29

**Comment by nicksellen** [comment]
The idea we had for an easy solution is to copy the name into the history entry (so it would be frozen in time for ever after), and maybe the bell notification too.

**Comment by dwaxweiler** [comment]
@nicksellen I agree that this would be a good enough solution for now.

**Comment by mvellasco** [comment]
Hey there, I'd like to work on this issue, is there anyone already on it?

**Comment by nicksellen** [comment]
@mvellasco yup, nobody is working on this currently! what level of support do you think you'll need in order to work on the task? are you generally familiar with the karrot software as a user?

**Comment by mvellasco** [comment]
@nicksellen I think I understood well the scope of the work, and yes I'm fairly familiar with the software as a user and I've made a small contribution to the software a few years back. If I get stuck I'll ask for some help, is that okay?

**Comment by nicksellen** [comment]
Sounds great @mvellasco :) feel very welcome to ping me for anything, and I'll be happy to review your contributions. Thanks!

Out of curiosity then, are you in one of the group's that use karrot?

**Comment by mvellasco** [comment]
@nicksellen Right now I'm not in any groups, I'm trying to set up one though in my local town(Campos dos Goytacazes - Rio de Janeiro - Brazil). About the solution, you guys had in mind to copy the user data into the history model, it might be even simpler if I didn't overlook anything, how about instead of adding a new DB field for that we just add another filter to the query for users matching if they have a GROUP_LEFT type history in the current user's group? I took the liberty to make a draft implementation and no tests broke so it should be fairly safe. In any case, let me know so I can submit the PR alongside the bell notification as well. Thanks!

**Comment by nicksellen** [comment]
Thanks! I replied over on the PR :star:

**Comment by nicksellen** [comment]
Moved to codeberg https://codeberg.org/karrot/karrot-frontend/issues/1619
