### ISSUE TITLE
Choice between "wall" or "activities/pickups" as the default page for a place

### ISSUE THREAD

**Issue by brnsolikyl** [karrot-dev/karrot-frontend#1703]
In cases where the wall is the most used feature for a specific place, it would be great to be able to choose while editing the place to either make the "Wall" or "Activities/Pickups" as the default page when coming to a place's page.

**Comment by tiltec** [comment]
This is also connected to #1297 as it's meant to make place conversations more visible.

**Comment by brnsolikyl** [comment]
Yes. It's also a way to improve navigation for places used mainly for conversations

**Comment by nicksellen** [comment]
The idea is to discuss this more widely in a forum post, and to close this issue once the post exists!

**Comment by brnsolikyl** [comment]
https://community.foodsaving.world/t/how-to-make-places-more-suitable-for-discussions/591

**Comment by brnsolikyl** [comment]
Since this is sort of a constant need in the groups I'm a part of, I'd like to start working on this, at least on the frontend. But I would need some help, someone to set up at the backend which one is the default (wall or activities). I remember that was one solution we discussed at some point...

I could also start with a mockup and upload them here and at the forum.

**Comment by brnsolikyl** [comment]
I did the mockup of how it would look like when creating a new place, because on the place page it should be just a matter of which tab is seen first by default

Maybe @dwaxweiler has an opinion on this, since we talked about this before on the forum.

![place_create](https://user-images.githubusercontent.com/25367304/130413526-4585bebd-bc2e-49fd-8e97-418bd23c6f14.png)

**Comment by dwaxweiler** [comment]
@brnsolikyl I like the wording "main focus" in your question. I would add as an explanation that this defines only the page that opens when you click on a place and that it does not hide any.
