### ISSUE TITLE
Streamline application flow

### ISSUE THREAD

**Issue by tiltec** [karrot-dev/karrot-frontend#2080]
The usual process to join a group right now is to sign up, find the group and submit the application. The alternative is to send out invitations. Our statistics show that invitations are not used a lot: last 6 months on karrot.world: 96 accepted invitations, 395 accepted applications. Invitations were predominantly used in three groups: two DLC groups (64, 87) and EfA (29).

Our idea in #1984 was to remove the invitation flow in favor of a more streamlined application workflow, starting from the group preview page (e.g. https://karrot.world/#/groupPreview/37).

Reasons for removing the invitation flow were mainly to just have one way to become a group member, which should reduce conceptional complexity for Karrot users. We also want to focus our time on building refined features for Karrot, instead of having many half-baked ones.

It doesn't seem strictly necessary to remove invitations very soon, but we could hide them a bit more first while we streamline the application flow.

**Comment by brnsolikyl** [comment]
A summary of the flow as it is now (for users invited to an existing group):
User gets link to the groupPreview page -> clicks on sign-up button -> sign-up page -> (back to groupGallery page) confirms e-mail -> lands at e-mail verification page with "take me home" button (to groupGallery page) -> finds group of interest again -> application

One idea to skip a few steps:
... -> confirms e-mail -> groupPreview page that the user wanted to apply in the first place, perhaps with a "E-mail verified successfully" notice -> application

**Comment by brnsolikyl** [comment]
Just got complaints from unrelated people in Solikyl, two days in a row, about joining a group on Karrot for the first time.

One of them said that she did held an introduction for a couple of people to join the group, but that they "got stuck in Germany". Asking more I found out that she meant the Playground group.

A similar complaint from another one was that it was not easy to find the right group to do the application after signing up, and that people did not understand why they ended up at the Playground.

Related to https://community.foodsaving.world/t/how-to-handle-the-spam-in-the-playground-group/486/10

**Comment by tiltec** [comment]
That sounds annoying! Yeah, playground-auto-join might be too confusing given that people who visit the site first might not understand the concept of a "group" at all...

Let's make the playground group closed and don't mention it during signup, then see how it turns out!

**Comment by tiltec** [comment]
Do we still need the "open groups" feature at all? As far as I know, all active groups have been migrated to using applications. This would simplify some logic and enable us to refine the application flow without thinking about implications for open groups.

**Comment by brnsolikyl** [comment]
Open groups don't seem very relevant now... :)

**Comment by brnsolikyl** [comment]
I think I'll start working on the bit about removing invitations, but only on the frontend. My idea is to keep the invitation button on the members page and just make it show a dialog with the link to the groupPreview page to be copied. I'm thinking it can still be useful to preserve invitations in the backend so it can be used in the future during the group creation process. What do you think @tiltec and @nicksellen ?

**Comment by brnsolikyl** [comment]
A few meetings ago I presented the idea above and it was accepted. So I'll start working on this little tweak. I'm thinking of something look like this:

![image](https://user-images.githubusercontent.com/25367304/114935844-f5db9680-9e3b-11eb-83cb-78b36a3a2bfc.png)

I'm curious to know if @larzon83 would have any other suggestion for this ;)

**Comment by larzon83** [comment]
> I'm curious to know if @larzon83 would have any other suggestion for this ;)

Generally it's good like this. Just a few cosmetics:
- I would add a "close" button
- the input looks a bit unusual :)
- Headline: "Invitation Link" (?)

**Comment by larzon83** [comment]
@brnsolikyl this issue can be closed, right?

**Comment by brnsolikyl** [comment]
Well, invitations have been removed from the members page, but we still need to streamline signup and application flow. I wonder what to do with the issue... just leave it open or maybe another one with more focused information?

**Comment by larzon83** [comment]
Uh sorry, didn't read the issue 🙈 I would keep this open.

**Comment by brnsolikyl** [comment]
Alright, I'll just edit the title then. :)
