### ISSUE TITLE
Feedback to be given only after an activity ends

### ISSUE THREAD

**Issue by brnsolikyl** [karrot-dev/karrot-frontend#2184]
The behavior now is that Karrot prompts you to give feedback to an activity right after it has started.

The proposal is that feedback can be given only after the activity has ended. For activities that do not have an end time, there seems to be a default of half an hour.

Quoting Nick:
>  we mark the activities `is_done=True` by checking for `date__startswith__lt=timezone.now()` which seems like it should be `date__endswith__lt=timezone.now()`

**Comment by nicksellen** [comment]
We had more discussion in rocket chat about it here --> https://chat.foodsaving.world/channel/karrot-dev?msg=pDCYemqn5b9F56F4x

I made this suggestion, which seemed to be accepted:

> So maybe have it so max delay for being able to give feedback is 1h after it starts. 
>
> For activities less than 1h that would mean you can only feedback after the end.
>
> For ones longer than 1h you can give feedback 1h after it starts.

**Comment by brnsolikyl** [comment]
Damn bot! Although for this issue another round of 90 days might be useful. Next time I'll let the bot do its thing.

**Comment by pogopaule** [comment]
The Freiburg group is now working on it.
