### ISSUE TITLE
Display all places by default if none of them is marked as cooperating

### ISSUE THREAD

**Issue by wetneb** [karrot-dev/karrot-frontend#2289]
**User story:** I start a new group and add a few locations on the map. Since the group is new, none of the places are cooperating yet.
If another user joins the group, by default they will not see any place on the map because only the cooperating ones are shown. Perhaps that is a bit confusing?

**Suggestion:** Only filter out inactive locations if there is at least one active location. The toggle can still be used to enable the filtering if need be.

**Alternatives considered:** I am wondering if all locations should be shown by default, no matter whether there are active ones or not. When I first used Karrot I was looking for a place, did not see it on the map and did not realize it was filtered out by this toggle. I am not sure if it is a widespread reaction of course…

**Comment by brnsolikyl** [comment]
I have a slightly related experience: when looking for a place on the list of places I reach the end without finding it, because it was recently marked as "negotiating/idle". Given this and your experience I'm positive about filtering out inactive/not cooperating places and archived ones and leaving the idle ones.

Another point that might improve usability: move the toggle for showing all places to the bottom of the list. What do you think @wetneb ?

**Comment by wetneb** [comment]
Hello @brsolikyl, thanks a lot for chiming in!

I am not sure changing the position of the toggle would have improved things much for me. If there are some active places this is going to push it further down, making it even less visible. And pressing the toggle will change the number of elements in the list, so it will change the position of the toggle - I don't think that is a very nice user experience.

One problem is that the toggle does not have any label attached to it (only a hover text). So it is quite mysterious! If I am curious about what this button is doing, I can find out by hovering it, but that requires a bit of initiative.

One more radical option would be to remove this toggle altogether and always show all places. The list of places is already sorted by status anyway, so if you are only interested in the active ones you can just look at the top of the list and ignore the rest. Some vertical scrolling or a "load more" button could be added to keep the height of this component in control. For the map, the inactive places could be made less prominent, so that they don't clutter the map view but are still displayed.

**Comment by brnsolikyl** [comment]
Yes, I was actually thinking more in the direction of adding a "show more" button to extend the list, a bit in the style of the one already in place at the menu above Places.

I also like the idea of displaying places with other statuses discreetly on the map, maybe a little dot would make it work. As you said, displaying all places as it is now would clutter the map a lot, especially in groups with lots of places.
