### ISSUE TITLE
Jump to conversation when clicking on conversation notification

### ISSUE THREAD

**Issue by dwaxweiler** [karrot-dev/karrot-frontend#2318]
**Steps to reproduce**
1. Make sure to have a conversation listed under the conversations icon.
2. Click on the conversations icon.
3. Click on the conversation.

**What happens**
You are redirected to the top of the wall page. If you have many pickups listed on top of the page, you are confused.

**What should happen**
You are redirected to the conversation referenced on the wall page. This could be a jump or a smooth scroll to animation.

**Comment by brnsolikyl** [comment]
Do you mean a conversation started at the main wall, or also a conversation at a place wall? It would probably make sense for both, right?

**Comment by dwaxweiler** [comment]
Yes, this would make sense for both.

**Comment by dwaxweiler** [comment]
Yes, it is still important.

I think it should use the same behaviour as the solution for #2311 to be consistent.
