### ISSUE TITLE
Improve notifications for place conversations

### ISSUE THREAD

**Issue by brnsolikyl** [karrot-dev/karrot-frontend#2342]
Getting notifications for conversations taking place on a place's wall can be improved.

Currently, you would never get any kind of notification or be aware of conversation taking place in a place's wall unless you mark the place as a favorite or subscribe on the bell toggle. You are also automatically subscribed to a place wall if you write a message there. This appears to create some confusion, see https://community.foodsaving.world/t/introducing-store-wall-and-store-subscriptions/241/30

The challenge here is to strike the right balance of making place wall conversations visible enough without annoying people with unsolicited notifications.

Here's one idea on how to display notifications:
https://github.com/yunity/karrot-frontend/issues/1297#issuecomment-578417055

**Comment by nicksellen** [comment]
This seems useful still, I noticed the problem myself with some users of karrot.

**Comment by brnsolikyl** [comment]
I'd say we close this issue cause most of it was (partially at least) solved by the latest improved display of places. Seeing which places have active conversations or the number of messages on the wall might still be useful, but then we could just open another suggestion on the [forum](https://community.karrot.world/c/karrot/feedback-ideas/31)
