### ISSUE TITLE
bug: block with group preview cards on Safari Mac

### ISSUE THREAD

**Issue by larzon83** [karrot-dev/karrot-frontend#2346]
Layout corrupted:

<img width="947" alt="Bildschirmfoto 2021-04-18 um 08 20 38" src="https://user-images.githubusercontent.com/23213583/115136277-08fa8c00-a01f-11eb-8220-499bda9e3786.png">

<img width="681" alt="Bildschirmfoto 2021-04-18 um 08 20 49" src="https://user-images.githubusercontent.com/23213583/115136337-65f64200-a01f-11eb-97ef-40270d1ca539.png">

**Comment by nicksellen** [comment]
Ah it's interesting this just got marked as stale again, I saw it with my own eyes for the first time on Friday on my friends computer :)

**Comment by larzon83** [comment]
I remember :) Maybe I can fix it. Will try it this month.
