### ISSUE TITLE
Add a message to help confused Brazilians

### ISSUE THREAD

**Issue by nicksellen** [karrot-dev/karrot-frontend#2355]
Due to some confusion somewhere, we get quite a few lost Brazilians creating groups on karrot, thinking it's some kind of educational platform for professors/students :laughing: 

We could add a message somewhere (either on initial sign up, or on group creation) that uses geo ip to detect users in Brazil (approximately), and show a message in Brazilian Portuguese to explain that karrot might not be quite what they are looking for... We already have geo ip that returns co-ordinates to the frontend, although possibly could benefit from providing more info from the backend if poss (e.g. country code).

Some background (from https://chat.foodsaving.world/channel/karrot-world-admin?msg=iXbBNRQhRg3rqRbjv):

>  Just looked up the name of a person who recently applied to the Playground, a Brazilian woman, and found out she works at this multinational corporation that is a "global provider of high-quality postsecondary education", so they own universities in different countries including Brazil - laureate.net. So there's probably something to my guess that people are confusing Karrot with Kahoot! Just gotta figure out the source... Maybe some office worker trying to advise their schools gave the wrong link on an e-mail, or maybe some blog post. I just got so curious!

**Comment by brnsolikyl** [comment]
I can contribute with the message in Portuguese, being a native speaker... If someone else would like to implement it, please go ahead. :)

> Olá! Você tem certeza que está na plataforma correta? Você não confundiu Karrot com Kahoot, né? Para clarificar, este site **não** é de ensino ou para projetos educacionais. Se você é professor/a ou aluno/a, deve estar procurando então outra plataforma com nome similar. Mas já que você está aqui, aproveita para ler mais sobre Karrot e como organizar sua comunidade local.

**Comment by brnsolikyl** [comment]
Is this still something relevant? I couldn't tell since we closed our previous chat and lost the notifications for groups being created.

**Comment by nicksellen** [comment]
I have a feeling not, as before there was a bunch of confusion Brazilian groups on the map, and there doesn't seem to be now...

(also reminds me it would be nice to publish the karrot group notification thing to the matrix room... (or even somewhere in karrot?))
