### ISSUE TITLE
Rename group description to group information

### ISSUE THREAD

**Issue by nicksellen** [karrot-dev/karrot-frontend#2356]
See discussion over at https://community.foodsaving.world/t/remove-or-move-internal-group-description-aka-group-description-visible-for-members/259/4

The ways groups use the "description" field is usually more like _information_ for the people in the group. They put things like links to other places (e.g. google docs, facebook groups, website info, etc...).

It would seem useful to make two changes:
- rename the field `description` -> `information`
- add a menu item in the left sidebar for accessing it

**Comment by nicksellen** [comment]
Hey @jalvarez302, and welcome! It would be worth having a look at our [How to get involved!](https://community.foodsaving.world/t/how-to-get-involved-onboarding-into-the-karrot-team/661) page, which will give you an overview of the whole project.

Maybe then a good idea to head over to our [chat](https://chat.foodsaving.world) and chat a bit more, can find out about your skills, interests, and motivations (avoiding filling up this issue with that).

How does that sound?

**Comment by larzon83** [comment]
@jalvarez302 We could also have a video call if you want. ;)

**Comment by kkreine** [comment]
Hello, it looks as though this issue needs further work. I'm happy to start working on it if it is still needed.

**Comment by linalex1** [comment]
Hello, is this issue still unresolved? I would love to take a look at it and try to fix it if it is still an issue.

**Comment by kkreine** [comment]
Hi, I'm running a little late but will update the PR tomorrow
