### ISSUE TITLE
Include activity description in reminder emails

### ISSUE THREAD

**Issue by nicksellen** [karrot-dev/karrot-frontend#2365]
From a comment in [the playground group](https://karrot.world/#/group/16/wall):

> **Them**: Is it possible to customise the activity reminder email?
> **Them**: On a specific case send to the users that applied to the activity a check list and other information. In this period maybe add specific info on how the activity should take place following local sanitary regulations or decision of the team. Example: Bring facemask, have a negativ test not older then 72h ect. 🙂

> **Me**: So maybe if the activity description was included in the reminder email that would make that possible?

> **Them**: Sounds a good idea 🙂

We have two kind of activity emails:
1. the daily activity notification one - that gets sent out in the evening to tell people about their activities, and any that are not yet filled
2. activity reminders - sent out 3h before the activity they signed up for is due to start

I think this makes most sense for 2, but maybe could be included in 1 as well (for their signed up ones only?).

**Comment by micaelagimenez** [comment]
Hello, I'd like to help with this issue. I've been looking at the code so I was wondering if what needs to be done is to add the Description field in the Activity model as a parameter to the prepare_activity_notification_email function or if it should be added to another function in another file. I'd be happy to help, so please let me know if this is still open.

**Comment by amengsk** [comment]
hey @micaelagimenez i'm not a maintainer here but i think it should be even easier than that actually! it looks like the emails are generated by templates `./karrot/activities/templates/activity_notification.mjml` and `./karrot/activities/templates/activity_notification.html.jinja2`.

in those templates you already have access to the `Activity` instances, so you should be able to access the description field directly with `activity.description`

if your up for it then i think it would be really useful to work on it, i can really relate to the user story there!

**Comment by micaelagimenez** [comment]
Hi @amengsk ! Thank you for the tip, that makes sense so I'll add it to the template then!

**Comment by titanventura** [comment]
Hey, So is the addition completed ? Or shall I work on it ?

**Comment by tiltec** [comment]
I think this is still open, you can work on it!

**Comment by amengsk** [comment]
i would reopen this

**Comment by nicksellen** [comment]
re-opened, and marked as important, so it'll stay open.

is there a reason this is particularly important for you @amengsk? (and do I assume correctly that you are part of Foodsharing Warszawa?)

**Comment by amengsk** [comment]
thanks! i just relate to the user story and it seems like a good first task for new contributors, so worth leaving open (but no i am no longer active in that group)

**Comment by nicksellen** [comment]
Move to codeberg https://codeberg.org/karrot/karrot-frontend/issues/2365
