### ISSUE TITLE
Add pagination for activities

### ISSUE THREAD

**Issue by nicksellen** [karrot-dev/karrot-frontend#2388]
Currently we return up to 400 (soon 800) activities per "page", as we don't have pagination implemented on the frontend for activities.

See: https://github.com/yunity/karrot-backend/blob/36818f990781c1e775e560fa43c9d616fcbd5dec/karrot/activities/api.py#L181-L187

We recently had the issue that the 400 limit wasn't enough https://github.com/yunity/karrot-frontend/issues/2384, which was resolved by increasing to 800, but the proper solution is to actually have pagination :)

**Feb 2022 update**: 800 is not enough any more, for Foodsharing Warszawa (1025 currently).

**Comment by tiltec** [comment]
For this, we need to remove the frontend assumption that all activities are present. All pages with activities should then care about their own data retrieval, ideally as non-global "page data". As different pages need different filters,  reusing activities between different pages wouldn't make sense. 

A special case are activities needed for topbar entries, mostly as activity conversation and notification metadata. Those probably could stay in a global datastore.

**Comment by tiltec** [comment]
Resolved with #2567
