### ISSUE TITLE
Notifications still sent after leaving group

### ISSUE THREAD

**Issue by brnsolikyl** [karrot-dev/karrot-frontend#2411]
This is the case:
I left a group and still got a push notification and a notification on Karrot under Replies (see image) from a conversation I was participating in. I cannot access the message itself, it returns `Message not found` but I could still read the content of the message at the notification itself.

![image](https://user-images.githubusercontent.com/25367304/125096748-bb4d6700-e0d5-11eb-8f05-9729c5a48c06.png)

Apparently no e-mail notification has been sent out

**Comment by manasviparikh** [comment]
Hello,
I am new to open-source contributing, and I was wondering if this would be a good first issue to try to tackle? If so, I would like to claim this issue.
