### ISSUE TITLE
Store users timezone

### ISSUE THREAD

**Issue by nicksellen** [karrot-dev/karrot-frontend#2415]
Currently, if a user is in a timezone different to that of the group, this stuff happens:
- notifications will be sent using group timezone, which may differ from their local one
- setting times in the UI when in a different timezone to the group is ambiguous (will be in browser timezone)
- ... at least browser will always display the times in the users local browser timezone

Browsers aren't actually very good at handling timezone calculations, they just have the concept of the one they are in (there are some timezone APIs on the way, and libraries, but [last time I looked](https://github.com/yunity/karrot-frontend/issues/959#issuecomment-372175803) had various downsides - those could be fixed now though). A change was made a while back (https://github.com/yunity/karrot-backend/pull/1022) that means from the API data we know the local time of an activity. This could be useful in some places.

That change was done as part of solving https://github.com/yunity/karrot-frontend/issues/959 - but I'm not sure the issue is so valid now, as karrot groups might have valid reasons for understanding users in multiple timezones (if only the karrot group about organising karrot itself, but also people might interact with their local group whilst travelling elsewhere, and other groups might be inherently across timezones).

So, I'm thinking the idea is to keep track of the timezone of each user in the database. We could detect it when creating the user account, but also allow them to set it manually in the profile. We have to ways to detect it:
1. using jstz detect library, which we use when creating groups already
2. our geoip endpoints also return timezone info from the ip

1 seems like the simplest option, as we already have the library.

To break up the work into a few smaller steps, the components might be:
- add db column and auto-populate existing users if empty (with geoip timezone? or group timezone?)
- add API to set it manually + add it to the user create / edit forms
- use the user timezone when sending backend notifications/emails, perhaps display timezone abbreviation to clarify in cases where it differs from group?
- possibly add some UI when you are in a different timezone to the group and doing time-related setting, just to make it clear
- consider prompting to set timezone if browser is different timezone to current user setting
- consider displaying some times in multiple timezones (e.g. could have nice tooltip/popover thing on the times that show the time for all the timezones that are existing across the group members, a bit like we do manually in the community forum)

**Comment by nicksellen** [comment]
(I put it as ready for development, lower priority, rather than discussion, because I consider the current behaviour _wrong_ in some cases - but also welcome discussion, could move it into a discussion milestone if there is resistance to this idea)

**Comment by kxc3244** [comment]
Hello @nicksellen , I actually believe this could be a really nice improvement to the UX. 

And it would be great if I could get this assigned. I would most likely go with the GeoIP route as this application is global and the users do probably travel so it would help in that scenario. 

Like I mentioned the timezone of users probably changes, it would be helpful to add a prompt aside from the settings options to change the timezone to give the user a message like, "Looks like you're in a different timezone, would you like us to change to your current timezone?"

**Comment by nicksellen** [comment]
Sounds great! I'd suggest to break up the task into smaller pull requests that can be merged as we go, as there are quite a lot of places that will need code changes. E.g. the db column can be added as one PR without anything else, and later the API added, etc. And later the frontend, and later the helpful message....

How does that sound?

What support would you need to get started on the task? Do you already have the skills/knowledge you think is needed to complete the task?

(I'm away travelling at the moment, so can't do very much for the rest of this month)

**Comment by kxc3244** [comment]
Yes, I have the skills required for the tasks and I'll make sure to break the tasks down as fundamentally as possible. 

The only questions I have are basically, do you need me to follow any style guide and for vue are you using composition API or not. the last thing is you have any dev docs that you follow for the architecture of the application that would be helpful.

**Comment by nicksellen** [comment]
Great!

For code style, we have strict linting rules that will be enforced by the tooling (locally and in CI). For the wider dev docs we have https://docs.karrot.world/ but it's not great, incomplete and probably out of date in places. I'd be interested to know what kind of eocs you'd find useful, it's an an area I'd like to improve on.

We don't use the composition API yet, we are still on Vue 2 as we haven't upgraded to Quasar 3 yet. That's quite a lot of work in itself.

We find it's best to push your code earlier rather than later, and you can do a Draft PR and get any feedback earlier on, rather than working away for ages. Even though I'm travelling I'll try and give feedback when you need it, also @tiltec is the other developer who might be able to review and guide, although he is also away travelling (both of us on cycle tours), so I suspect his time is even more limited than mine.

Thanks, and hope you enjoy the coding.

Oh, and one more thing, where did you find out about Karrot?

**Comment by brnsolikyl** [comment]
Just removed the stale label but want to know the status of this issue... Have you started working on it, @kxc3244 ? Any roadblocks?
