### ISSUE TITLE
Booking slot of activity that has started does nothing

### ISSUE THREAD

**Issue by dwaxweiler** [karrot-dev/karrot-frontend#2426]
**Step to reproduce**
1. Create an activity that should happen within a certain time interval, i.e. set a start and an end time.
2. Wait until the start time has past.
3. Click on the empty slot.
4. Click "Yes, of course!" in the pop-up.

**What happens**
Nothing happens; The slot stays empty, even after refreshing the page.
In the developers tools, the request's response is a 403 (Forbidden): `{"detail":"The activity is in the past.","error_code":"permission_denied"}`

**What should happen**
The slot shows your picture to confirm it is booked by you, or an error message is shown.
Personally, I do not have a clear preference as I could think of arguments against and for allowing booking slots of activities that have already started, so I suggest to show an error pop-up for the moment.

**Comment by brnsolikyl** [comment]
Yes, I think there are both cases, when it makes sense to be able to join after it started and when it does not. I myself have wanted to join a pickup that had a set time but was actually quite flexible within a time period, so it's always unclear when people join in late to save the pickup/activity from being missed. For that reason I'd prefer to leave it open for the user to choose, after receiving a warning.

**Comment by dwaxweiler** [comment]
This bug still needs to be fixed. :)

**Comment by nicksellen** [comment]
I implemented this backend part to allow to join started activities. It would resolve the issue if we just merge that as it is.

An optional extra would be the warning on the frontend, do you think we should do that before deploying it?

**Comment by brnsolikyl** [comment]
A warning would be nice indeed! :)

**Comment by nicksellen** [comment]
How about this? You need to then check the checkbox to join.

![confirmstarted](https://user-images.githubusercontent.com/31616/143909502-8f0736a3-9d74-4c56-9015-0e63cabfb0f0.png)

**Comment by brnsolikyl** [comment]
Looks good to me! Annoying having to check the box and then confirm, but that's the point!
