### ISSUE TITLE
No password policy on sign up page

### ISSUE THREAD

**Issue by jayant766** [karrot-dev/karrot-frontend#2436]
When I go for sign up on the website I found there is no password policy i.e user can create there account by simply typing their mail and password to J (one word password)

Some policies suggest or impose requirements on what type of password a user can choose, such as:

the use of both upper-case and lower-case letters (case sensitivity)
inclusion of one or more numerical digits
inclusion of special characters, such as @, #, $
prohibition of words found in a password blacklist
prohibition of words found in the user's personal information
prohibition of the use of company name or an abbreviation
prohibition of passwords that match the format of calendar dates, license plate numbers, telephone
numbers, or other common numbers

https://user-images.githubusercontent.com/73739820/130286696-3f263011-bc0e-44d8-b599-ed99aa24e227.mp4

**Comment by tiltec** [comment]
Indeed, should be possible to add some validation in Django: https://docs.djangoproject.com/en/3.2/topics/auth/passwords/#module-django.contrib.auth.password_validation

Not sure if it should also be done in frontend, or we just forward to validation error messages from backend?

**Comment by jayant766** [comment]
Yes, we can add some validation in Django. Just tell me the exact location of the file where I can put the code.

**Comment by tiltec** [comment]
I think this might be a bit more involved, so setting up the dev environment and writing some test might be good. I wonder if you would be up for this?

Also, it would be good to change the frontend to communicate the new validation rules to users when signing up or changing their password.

**Comment by rheidem** [comment]
Hello! I have not contributed to this project, but would love to tackle this! Any suggestions on where to start?

**Comment by nicksellen** [comment]
@rheidem sure! First step would be setting up the dev environment, this task requires working on the backend, so head over to https://github.com/yunity/karrot-backend and see how you get on.
