### ISSUE TITLE
src/locales-foo seems unneeded

### ISSUE THREAD

**Issue by tiltec** [karrot-dev/karrot-frontend#2437]
I just discovered https://github.com/yunity/karrot-frontend/tree/master/src/locales-foo, seems to be wrongly committed and merged. I guess we can delete it? @nicksellen

**Comment by nicksellen** [comment]
Ah, sorry for delayed response! Yes, I agree, seems to be accidentally committed (or some function neither of us can recall!). Seems to have my name all over the git history...
