### ISSUE TITLE
Link to subscribe for ICS calendar not showing

### ISSUE THREAD

**Issue by brnsolikyl** [karrot-dev/karrot-frontend#2449]
Link shows fine as supposed to be when at the place page or the activities page. It doesn't show at the wall page when you have your upcoming activities at the top.

![image](https://user-images.githubusercontent.com/25367304/140808921-5196fc90-43b2-48e8-9470-147140d2173a.png)

**Comment by brnsolikyl** [comment]
Maybe @amengsk would like to fix it? ;)
Although I'm not sure what the fix should be like... Subscribe to all activities?

**Comment by nicksellen** [comment]
I also noticed the same, although I, less helpfully, only wrote about it on the closed original issue --> https://github.com/yunity/karrot-frontend/issues/2334#issuecomment-963379067 (plus a couple of other niggles).

Basically, it shows up fine on the activities page, but not at the top of the wall. I think either it could:
- be hidden in that view
- do the same as the subscribe button on the activities page (subscribe to all activities)

**Comment by amengsk** [comment]
hi folks long time no sea!
sure i will have a look at this and nick's comment on the original issue
stay tuned
