### ISSUE TITLE
Use multiword component names

### ISSUE THREAD

**Issue by nicksellen** [karrot-dev/karrot-frontend#2463]
New vue style guideline --> https://vuejs.org/v2/style-guide/#Multi-word-component-names-essential

Currently, I'll just disabled it in eslint config and link here.

**Comment by kkreine** [comment]
Hey @nicksellen, mind if I work on this? It looks like there's 22 components to be changed.

**Comment by nicksellen** [comment]
Yup, would be great!

The filenames will need changing too.

**Comment by kkreine** [comment]
@nicksellen I'm still working on this, I'll submit the PR in the next few days
