### ISSUE TITLE
Bug clicking on entry in place list when already on the place

### ISSUE THREAD

**Issue by nicksellen** [karrot-dev/karrot-frontend#2469]
Steps to recreate:
- click on any place (you can be on any tab)
- click the place again (in the left menu)
- you suddenly have no tabs selected, and no content is displayed on the main space

Just got introduced with #2444

**Comment by brnsolikyl** [comment]
Yes, another related bug I noticed is when you click on a notification for a message on a place wall, which does not take you to the message, if the place has Activities tab as default view

**Comment by nicksellen** [comment]
Released in v9.6.1 https://community.karrot.world/t/karrot-release-updates/466/11
