### ISSUE TITLE
Unsolicited e-mail notifications for applications

### ISSUE THREAD

**Issue by brnsolikyl** [karrot-dev/karrot-frontend#2495]
On the [notification settings page](https://karrot.world/#/settings#notifications) you can choose whether or not to get e-mail notifications about new applications to your group.
![screenshot_notifsettings](https://user-images.githubusercontent.com/25367304/152037388-3c1ec08d-fe17-4059-ad30-5a56db163b45.png)

However, it is not clear from the description that this also subscribes you to all application conversations, including the applications that you have not replied to. We've got feedback from at least two groups that this is either confusing or inappropriate.

A suggested improvement is to not subscribe for all application conversations that one does not reply to, but still get an e-mail notification (when box is checked) whenever someone applies to the group.

**Comment by Chinchuluun1029** [comment]
Hello, is this issue resolved? I tested the scenario with 2 email addresses that are members of a group (that both checked New applications checkbox) and had a 3rd account that sent an application and message on the application and none of the subsequent messages were emailed to the two members. If this is not the desired outcome, can you please elaborate on the scenario?

**Comment by brnsolikyl** [comment]
Hi @Chinchuluun1029 and sorry for the late reply.

The issue is still unresolved. I noticed this on my group and confirmed the issue by looking at postal.karrot.world, that the e-mails were actually being sent to non-participants in the application conversation. Also, another group reported the same problem to me.

I'm not sure how to reproduce it though.

**Comment by brnsolikyl** [comment]
Got this confirmed again today by @dwaxweiler . As it's apparently not the case with everyone and could not be so easily reproduced, I'll mark it as a bug.

**Comment by brnsolikyl** [comment]
Got two cases confirmed again from my group. Since it is quite annoying for many people I marked the issue as important.
