### ISSUE TITLE
Writing private messages during application process

### ISSUE THREAD

**Issue by nicksellen** [karrot-dev/karrot-frontend#2496]
There is probably a bug somewhere here... not exactly sure where.

As an applying user I cannot write private messages to people (I can see their profile, but there is no message button).

But a member in the group _is_ able to write me a private message (we have no common groups).

So either:
- we should show the message button for applying user
- we should totally disallow private messaging in that case

In places we have logic to access users based on group membership AND active applications, but maybe the frontend showing the message button doesn't include this.

Needs some investigation.

**Comment by manasviparikh** [comment]
Hello,
I was wondering if this issue has been resolved or if there was any more information/investigation done on this bug?
