### ISSUE TITLE
Issue with accents and umlauts

### ISSUE THREAD

**Issue by dwaxweiler** [karrot-dev/karrot-frontend#2502]
**Step to reproduce**
1. Use Firefox on a Linux operating system (Ubuntu-based Pop! OS in my case).
2. Type a letter with an accent or umlaut into one of the input fields, e.g. é or ö. 

**What happens**
The letter appears without its accent or umlaut.

**What should happen**
The letter appears with its accent or umlaut.

I have observed this issue from version 9.6.0 on, but I have not gone back to the previous version to confirm it. It is the only website I use with this issue.

**Comment by amengsk** [comment]
weird. i tried (also with firefox and linux) but i dont have this problem on my side. try without extensions maybe?

**Comment by nicksellen** [comment]
Hmm, yes sounds odd!

I manually deployed v9.0.0, can you check there? Much of the site probably won't work, as it will be out of step with the backend, but at least the login form is visible! --> https://v9.0.0.dev.karrot.world/#/login ... if that works we can keep doing it to narrow it down...

**Comment by dwaxweiler** [comment]
@nicksellen Thanks for the deployment! There, accents and umlauts work for me. @brnsolikyl what about you for é?

**Comment by brnsolikyl** [comment]
Yés, it wórks fine there! :) Every possible accent I could think of in Portuguese and Swedish worked.

**Comment by nicksellen** [comment]
Ok, I deployed a couple more versions, can you check them @dwaxweiler 

- [v9.0.0](https://v9.0.0.dev.karrot.world/#/login) works
- v9.1.0 ?
- v9.2.0 ?
- [v9.3.0](https://v9.3.0.dev.karrot.world/#/login)
- v9.4.0 ?
- [v9.5.0](https://v9.5.0.dev.karrot.world/#/login)
- v9.5.1 ?
- v9.6.0 broken

**Comment by dwaxweiler** [comment]
@nicksellen, thanks! Version 9.3.0 works fine, version 9.5.0 does not.

**Comment by nicksellen** [comment]
ok, getting there! so now try [v9.4.0](https://v9.4.0.dev.karrot.world/#/login) ... then I can go to looking at changelogs...

**Comment by brnsolikyl** [comment]
v.9.4.0 working here!

**Comment by dwaxweiler** [comment]
@nicksellen, for me too!

**Comment by nicksellen** [comment]
Hmm, interesting I'm not seeing much in the [changes](https://github.com/karrot-dev/karrot-frontend/compare/v9.4.0...v9.5.0) yet... 

The most interesting dependency change is quasar from 1.15.21 to 1.15.23 (although not a big increase).  The quasar release notes are here https://v1.quasar.dev/start/release-notes#introduction and one of the changes is about the QInput (text input):

> fix(QInput): restore caret position in textarea [#9915](https://github.com/quasarframework/quasar/pull/9915) ([#9939](https://github.com/quasarframework/quasar/pull/9939))

... but that doesn't seem a very significant change.

Needs a bit more exploring...

**Comment by nicksellen** [comment]
@dwaxweiler / @brnsolikyl can you try https://v9.5.0-olddeps.dev.karrot.world/#/login

(this is v9.5.0, but using the dependencies from v9.4.0)

**Comment by brnsolikyl** [comment]
Works! :)

**Comment by nicksellen** [comment]
Hmm, interesting. Can you try the input fields on https://v1.quasar.dev/vue-components/input

Any of these ones:

![egfields](https://user-images.githubusercontent.com/31616/156145738-1f75fad1-d8eb-409f-b900-3ba4acd41563.png)

**Comment by brnsolikyl** [comment]
Yep, not working there. So I guess you found the problem?

**Comment by nicksellen** [comment]
Getting there... can you try https://quasar.dev/vue-components/input#example--design-overview (which is from the v2 version of quasar, we are still on v1 series...).

**Comment by brnsolikyl** [comment]
Not working either

**Comment by nicksellen** [comment]
Aha, a bug in quasar :)

It's this issue https://github.com/quasarframework/quasar/issues/10198, which was closed as they couldn't reproduce it either.

I'm going to try and isolate the specific change in quasar that introduced it to make a better case for making an issue over there.

**Comment by nicksellen** [comment]
Can you try https://v9.5.0-patch.dev.karrot.world/#/login - I'm _hoping_ that one works...

**Comment by nicksellen** [comment]
This issue for firefox sounds like it's possibly talking about the same thing https://bugzilla.mozilla.org/show_bug.cgi?id=1077411 ... but some interaction with how quasar is doing things.

**Comment by brnsolikyl** [comment]
> Can you try https://v9.5.0-patch.dev.karrot.world/#/login - I'm _hoping_ that one works...

That one works!

**Comment by nicksellen** [comment]
How about https://v9.5.0-patchmask.dev.karrot.world/#/login ?

**Comment by dwaxweiler** [comment]
> How about https://v9.5.0-patchmask.dev.karrot.world/#/login ?

This one does not work for me, but the previous one does.

**Comment by brnsolikyl** [comment]
> How about https://v9.5.0-patchmask.dev.karrot.world/#/login ?

Does not work on Firefox, works on Chrome

**Comment by nicksellen** [comment]
Ok, two more, then I think I'll write on the quasar issue:

1. https://v9.5.0-quasar1.15.21.dev.karrot.world/#/login
2. https://v9.5.0-quasar1.15.22.dev.karrot.world/#/login

These are both v9.5.0 (which doesn't work), but with slightly different quasar versions....

**Comment by brnsolikyl** [comment]
None of the above works

**Comment by nicksellen** [comment]
> None of the above works

Oh :( that's disappointing, and slightly odd.

Ok, I made some codepens to just try out different quasar versions without all the complexity of Karrot:
- https://codepen.io/nicksellen/pen/rNYomrJ (quasar v1.15.21) <-- corresponds to karrot v9.4.0
- https://codepen.io/nicksellen/pen/XWzoRwY (quasar v1.15.22) <-- no karrot used this version
- https://codepen.io/nicksellen/pen/xxPmdNQ (quasar v1.15.23) <-- corresponds to karrot v9.5.0

**Comment by dwaxweiler** [comment]
Thanks for looking into this in depth, @nicksellen! Unfortunately, none of the codepens works for me.

**Comment by nicksellen** [comment]
Oh, getting odder. Can you try again... I made a little error where the text value wasn't saved anywhere... also, does the normal text input field below the quasar one work?

**Comment by dwaxweiler** [comment]
No difference! Yes, the normal input text field works in every codepen.

**Comment by tiltec** [comment]
@dwaxweiler @brnsolikyl 
Can you check if it works in Quasar v2? https://quasar.dev/vue-components/input

I tried it myself with typical German umlauts (äüö) in Firefox under Linux, but it all works fine. How do you actually enter the character? Do you have the character on your keyboard, do you use "dead keys" or do you use the "compose" key?

**Comment by nicksellen** [comment]
It doesn't work in quasar 2 (said here --> https://github.com/karrot-dev/karrot-frontend/issues/2502#issuecomment-1055248359)

**Comment by dwaxweiler** [comment]
@tiltec I enter all my umlauts and accents using dead keys with on US Internal keyboard layout.

**Comment by brnsolikyl** [comment]
I use the Swedish layout so the existing characters on the keyboard do work. Otherwise I use the dead key, which is the thing not working.

**Comment by tiltec** [comment]
Alright, I can reproduce it using the compose key. Interestingly, I could enter accents in the "email" input type: https://quasar.dev/vue-components/input#example--input-types 
Can you check if this also works with dead keys?

**Comment by nicksellen** [comment]
Ah great, I never managed to reproduce it :/

**Comment by dwaxweiler** [comment]
@tiltec You are right! The email input field also works for me.

**Comment by dwaxweiler** [comment]
@nicksellen If you have not done so, I would file a bug report at Quasar?

**Comment by nicksellen** [comment]
Yes, would be great @dwaxweiler :) I had wondered if @tiltec would be able to resolve it as he could recreate it locally... but seeing as it is faulty on the quasar site, it seems legitimately something they could investigate... though they'll also run into the difficulties of finding someone with a keyboard setup that reproduces it, and might disbelieve it as a real problem...

**Comment by tiltec** [comment]
Filing a Quasar bug seems the right step now! Can also get active there if they can't reproduce it.

**Comment by dwaxweiler** [comment]
I have asked to reopen the issue, you, @nicksellen, have found: https://github.com/quasarframework/quasar/issues/10198

**Comment by dwaxweiler** [comment]
This issue seems to be solved with the latest quasar releases 1.19.1 and 2.7.1; I have successfully tested the documentation examples. Once the PR #2537 is merged, this should be fixed.

**Comment by nicksellen** [comment]
Great! Good job keeping track of it. I just fixed up the issue with Sentry in that PR, so will merge soon.

Will take a bit longer before we deploy, as master currently has our vue2 upgrade in it, and I think that needs a bit more trying out before it's safe to deploy, quite a few things changes there as it was a big upgrade.

Beta testing of that is also welcome, we co-ordinate it over at https://karrot.world/#/group/191/place/1963/wall :)

**Comment by nicksellen** [comment]
Can you confirm if this is resolved on https://dev.karrot.world/ now? (that's on quasar 2.7.5).

**Comment by dwaxweiler** [comment]
@nicksellen Yes, it is resolved! Thanks

**Comment by dwaxweiler** [comment]
Solved with the latest release! Thanks

**Comment by nicksellen** [comment]
Woo, great!
