### ISSUE TITLE
Activity type filter shows archived types

### ISSUE THREAD

**Issue by nicksellen** [karrot-dev/karrot-frontend#2506]
The activity type filter on the activities page let's you choose activity types that have been archived (e.g. `Party` type is archived):

![archivedfilter](https://user-images.githubusercontent.com/31616/155130216-df322cee-95ea-4dcc-92cd-7e748b2255e2.png)

... one caveat is that it should still show archived activity types if there are activities for that type in view (as archiving a type does not delete the already scheduled activities).

**Comment by nitishvijai** [comment]
@yatharthchhabra and I will be working on this issue soon.
