### ISSUE TITLE
Possibly not loading enough information when joining a group 

### ISSUE THREAD

**Issue by nicksellen** [karrot-dev/karrot-frontend#2508]
After applying for a group and keeping the browser open, once in there were _loads_ of these kind of errors:

```
TypeError: t.activity.activityType is undefined
```

I _suspect_ it didn't properly load the activity types for the group after joining... it's ok after reloading the page. (There are probably other errors in this category too).

**Comment by yatharthchhabra** [comment]
Hi, I tried to replicate this issue by applying for a group with my dev console open and leaving the browser unrefreshed. After getting accepted, I was able to click around and I didn't encounter any errors. Am I doing something incorrectly or has this issue been resolved? Thanks
