### ISSUE TITLE
Infinite recursion issue

### ISSUE THREAD

**Issue by nicksellen** [karrot-dev/karrot-frontend#2512]
When visiting https://karrot.world/#/group/191/place/1448/activities/183343/detail in firefox I get this:

![toomuchrecursion](https://user-images.githubusercontent.com/31616/156155774-5ca640ce-75ce-4249-a522-5e513ee6f452.png)

![recusrionrouteisundefined](https://user-images.githubusercontent.com/31616/156155799-ffec7e6b-ebf1-4f28-a8fa-42ceb8b0d823.png)

That points to this line:

```js
hasView:function(){var t=this.$route.matched.length>0&&this.$route.matc
```

... in chrome it doesn't has the issue, but also doesn't open the conversation, just goes to the group wall....

**Comment by nicksellen** [comment]
Mobile view I think! (And hey!)

**Comment by pogopaule** [comment]
Can't reproduce it on master. I guess it has been fixed https://github.com/karrot-dev/karrot-frontend/pull/2501. I close this ticket.

**Comment by nicksellen** [comment]
Ah, thanks, sorry for that!

**Comment by pogopaule** [comment]
No worries! Was an easy bugfix for me 😄 

BTW saw you in a documentary!

**Comment by nicksellen** [comment]
> BTW saw you in a documentary!

Oh, do share more! I don't know if I know about this...

**Comment by pogopaule** [comment]
Starting at minute 18.30 https://www.ardmediathek.de/video/Y3JpZDovL3N3ci5kZS9hZXgvbzE1OTY3MzM/
