### ISSUE TITLE
Problem: we need unsafe-eval with how we use new vue-i18n lib

### ISSUE THREAD

**Issue by nicksellen** [karrot-dev/karrot-frontend#2522]
Ideally we can use the runtime build that doesn't need to compile messages, but we need to understand this better before we can do it. For now, I'm adding 'unsafe-eval' into our CSP policy...

**Comment by tiltec** [comment]
I somehow got vue-i18n to work with the runtime build, by compiling locales with vue-i18n-loader. But a lot is still broken, so I suggest to merge #2438 without waiting for this.
