### ISSUE TITLE
Problem: the frontend lets me use emojis that the backend doesn't recognise

### ISSUE THREAD

**Issue by nicksellen** [karrot-dev/karrot-frontend#2524]
I tried to use the `star_struck` emoji reaction (a face with red stars for eyes), but the backend tells me:

```json
{"name":["not a valid emoji name"]}
```

the POST request was to https://karrot.world/api/messages/79231/reactions/ with this body:

```
{"name":"star_struck"}
```

The frontend and the backend should agree on which emoji reactions are valid.

**Comment by manasviparikh** [comment]
Hi! I've been working on this issue for a bit and should be able to submit a PR shortly. :)

**Comment by tiltec** [comment]
I just remembered this script and wondered if we need to run it again with an updated SOURCE_URL? https://github.com/karrot-dev/karrot-backend/blob/master/karrot/conversations/management/commands/make_emoji_list.py
it creates the list of emojis and aliases that should be compatible with markdown-it-emoji and twemoji. maybe the list is out of sync? anyway, can also wait for your PR ;)

**Comment by manasviparikh** [comment]
I just submitted a pull request on the backend repo for this issue! have no idea how to link it to this issue on the frontend though... I ran the script ./manage.py make_emoji_list which updated the emoji list in make_emoji_list.py; the only issue is that it is not well formatted. It's two very large dictionaries.
