### ISSUE TITLE
Cannot create activities with unlimited participants

### ISSUE THREAD

**Issue by nicksellen** [karrot-dev/karrot-frontend#2548]
In the UI, if you delete the value for _max participants_ it shows _unlimited_, but when you try and save, the server says:

```json
{
	"max_participants": [
		"A valid integer is required."
	]
}
```

It should accept a null value to mean _unlimited_.

**Comment by tiltec** [comment]
Fixed in 3a7d33014c9ce0fb187834c390f46fc585a369ae
