### ISSUE TITLE
yarn lint:style is not working

### ISSUE THREAD

**Issue by tiltec** [karrot-dev/karrot-frontend#2553]
Output:

```
$ stylelint 'src/**/*.{vue,sass}'
App.vue: When linting something other than CSS, you should install an appropriate syntax, e.g. "postcss-html", and use the "customSyntax" option
...
src/App.vue
 20:5  ✖  Unknown word  CssSyntaxError

src/css/app.sass
 1:4  ✖  Unknown word  CssSyntaxError
...
```

This seems to be a leftover from the quasar upgrade.

Also, webpack-stylelint-plugin not configured yet in quasar.conf.js

**Comment by nicksellen** [comment]
I think for this case a Vue SFC can be treated as an HTML document, if that helps anything.

https://stackoverflow.com/a/5654471 says that sass is an older syntax to scss, so converting to scss could be an option if that seems to have better supported tools? Although https://stylelint.io/ says it supports both.
