### ISSUE TITLE
Don't subscribe everyone to issue conversation

### ISSUE THREAD

**Issue by nicksellen** [karrot-dev/karrot-frontend#2556]
Following proposal over here --> https://community.karrot.world/t/conflict-resolution-with-possibility-to-remove-user-from-group/201/40

> So when a conflict resolution begins, everyone in the group will get a bell notification about it, and only those with the “new conflict resolution process” notification enabled in their settings will be subscribed to the conversation and get an email about it. This notification is enabled by default, so the change we discussed and proposed was to not have this enabled by default, meaning that when a conflict starts, only an email and bell notification would be sent out to everybody, but not the e-mails about the conversation (unless you subscribe to the conversation manually, or write a message in it, which automatically subscribes you). Currently you cannot completely unsubscribe from the conversation at all, so this is a change in that behaviour.

That was agreed today in our weekly meeting.

So, this involves:
- making it possible to not be subscribed to issue conversations at all (currently it is enforced that you are _always_ in it, and can only lesson the notifications, but not step out completely)
- make the "conflict resolution process" notification type not add you to the conversation
- the only two people in the conversation initially should be the person who created it, and the person it is about

Everyone in the group will still get a bell notification and an email about it, plus a bell notification when it is near the end time.

We also discussed further improvements that can be made to conflict resolution, this is only a small intermediate, actionable step. We'll discuss more about conflict resolution in the upcoming Karrot Days --> https://community.karrot.world/t/karrot-days-2022-july-16th-17th/922

**Comment by brnsolikyl** [comment]
Solved - https://github.com/karrot-dev/karrot-frontend/pull/2582
