### ISSUE TITLE
karrot.world is down

### ISSUE THREAD

**Issue by dwaxweiler** [karrot-dev/karrot-frontend#2568]
My browser says `Unable to connect`. I have heard similar reports from others of my group.

**Comment by nicksellen** [comment]
Yes, sorry @dwaxweiler we are having some trouble with the server at the moment. After some OS updates, the server did not come back again after a reboot, we can enter into a recovery mode, but so far it won't boot normally.

We're looking at it! Quite frustrating here, normally these things are quite reliable...

**Comment by nicksellen** [comment]
We suspect one of the hard disks is broken, there are 2 disks in a raid1 configuration, and we've been trying to get the system to boot from the second disk, so far without success.

We are paying for some out-of-hours support for someone to connect a device that let's us access the system console (as if we were physically next to the machine with a keyboard and monitor), which should let us modify the boot settings.

It's unfortunate it's at the weekend, as the people are quite expensive!

**Comment by dwaxweiler** [comment]
@nicksellen Thanks for the updates! I cross my fingers that you manage to fix the issue!

**Comment by nicksellen** [comment]
I put a maintenance page up on https://karrot.world/ now, which refers to this issue, so it's the Official status updates place for now!

The support people seem quite helpful so far, and they have offered to put a new disk in, and connect the KVM (the thing that let's access the server console) within the next couple of hours.

**Comment by nicksellen** [comment]
Woo, they swapped the disk out, and it boots now. We have a bit more maintenance to do before putting it back online properly, but we're on the home run now.

**Comment by nicksellen** [comment]
We are back! :partying_face: :sparkle: 

The raid array is being rebuilt, and still some upgrades to continue another day, but for now that's a happy place to get back to.

The community forum is still offline, that always had an issue starting up after a reboot, but we're on that too (that causes a Server Error message to show on karrot when you load it).

**Comment by dwaxweiler** [comment]
Thanks so much to everybody involved!

I leave Nick's post on the forum here for reference: https://community.karrot.world/t/sorry-for-the-karrot-outage-today/956

How can I buy you a drink after that Saturday?
