### ISSUE TITLE
Users sometimes stay conversation participants after leaving group

### ISSUE THREAD

**Issue by tiltec** [karrot-dev/karrot-frontend#2571]
Just opening this issue to remember in future. I used this query to find affected conversation participants:

```
ConversationParticipant.objects.filter(conversation__group__isnull=False).exclude(conversation__group__members=F('user'))
```
Currently there are over 30k results on karrot.world, most of them activities, but also applications, places and offers.

Need to figure out if they are actually wrong, how this happens and how to clean up.

**Comment by brnsolikyl** [comment]
Now I noticed an old issue I posted about this was closed by the bot. I can confirm this problem:
https://github.com/karrot-dev/karrot-frontend/issues/2411

**Comment by brnsolikyl** [comment]
Got this issue confirmed in practice yesterday... I wrote at a place wall and a person who's been previously voted out of the group got the e-mail notification about my message and was able to reply it by e-mail, so their answer ended up on the thread.

I think it's a very important bug to work on and should be prioritized
