### ISSUE TITLE
Edit button inside activity edit preview should not be there

### ISSUE THREAD

**Issue by brnsolikyl** [karrot-dev/karrot-frontend#2592]
I found that when editing a series of activities and pressing the Preview button, there's also an edit button there and it's actionable. This creates quite a confusion!

![image](https://user-images.githubusercontent.com/25367304/192621680-cf742780-3abf-402a-a8e3-7de723ad41f4.png)

**Comment by nicksellen** [comment]
Here's the fix --> it's this line https://github.com/karrot-dev/karrot-frontend/blob/efe8f52a4d6d957db02769a38c0ad47bf26fa03a/src/activities/components/ActivitySeriesEdit.vue#L323 should have the `preview` attribute set (which was probably like it from when I added that feature)
