### ISSUE TITLE
Place display shows 0 messages when there are some

### ISSUE THREAD

**Issue by nicksellen** [karrot-dev/karrot-frontend#2594]
The place display will show 0 message count although there are messages.

![placemessagecount](https://user-images.githubusercontent.com/31616/193020653-77a554d2-fcb6-437e-9659-17e8a854943f.png)

This is because we don't track conversations that you are not part of.

I think it should not show any number at all in that case, as right now it's misleading.

It _could_ just show it for favourites, but I _think_ you can have notifications enabled for the wall, without the place being a favourite, and can have it as a favourite without being subscribed to wall notifications.

Fortunately, I think the status data from the backend will only have the `unread_wall_message_count` field if you are subscribed, so the presence of that field in the status object should be enough to determine whether to show a count or not.

![statusdata](https://user-images.githubusercontent.com/31616/193021439-5ad4a1cf-07d7-4aab-808d-72266fa91d5a.png)

**Comment by tiltec** [comment]
I mean, it will also show "0 messages" if you read them all… but the messages are still there!

But maybe the change you mentioned might be an improvement.

**Comment by nicksellen** [comment]
Probably just not showing at all when it's either a zero or not present, would make more sense to me. Perhaps in the same way that our bell notification doesn't show a 0 when there is nothing new.
