### ISSUE TITLE
[Feature Request] Past Activities

### ISSUE THREAD

**Issue by mwelsch** [karrot-dev/karrot-frontend#2595]
Hey,
It would be great to have something like "Past Activities" for a place in addition to "History". In this Tab you would be able to see (all?)  past activities. Maybe also with the feature to enable/disable this tab per place? Would be great for paid events, then I know immediately when the event was, and what budget we planned. Currently we keep this information manually, if somebody forgets to write it down it can be quite a pain to look through all our mail to find the correct information

If this is the wrong place for feature requests let me know :)

Thanks for all the work you've put in this project <3

**Comment by nicksellen** [comment]
Thanks @mwelsch, yes, I totally agree this makes sense, we've heard the same from a few groups.

I do wonder where it should go, my first sense would be to have another filter on the activities page, but that is getting quite busy now (there are quite a few changes not deployed yet):

![activitiespage](https://user-images.githubusercontent.com/31616/193092874-30348b95-1fb9-41c0-8ec9-670690188463.png)

... another option would be a totally separate page in the left sidenav (perhaps hidden below the "Show more" section?)

If we only had them on the place page (as a tab, for example), then there would be no _overall_ view across all the places...

Any thoughts? Sketches are very welcome to.

(I can't promise it'll be worked on right away, I'm in need of a bit of a break after an intense time working on it lately! hoping to get more devs wanting to contribute...)

**Comment by mwelsch** [comment]
I would seperate this feature, for a few reasons:
- too messy if everything is on one page
   - e.g. how do you display past AND upcoming events on the same page? 
- I want see the most recent activities on the top of my screen and scroll down for events that were longer ago

Some very professional photoshop mockups - I would opt to make idea 2 AND 3:
Idea 1:
![firefox_Y9mWzsJ7Nv_2](https://user-images.githubusercontent.com/31733941/193419280-421fda0f-baf0-4387-aeff-4faa5d6ac080.png)
![firefox_Y9mWzsJ7Nv-idea2](https://user-images.githubusercontent.com/31733941/193419282-c9c91ae9-9277-4992-a6be-2b33825fb788.png)

Idea 2:
![firefox_Y9mWzsJ7Nv_3](https://user-images.githubusercontent.com/31733941/193419299-f759947b-8d77-4fb7-85bd-fc96140cbd7e.png)

Idea 3:

![firefox_WRMRENEJth_2](https://user-images.githubusercontent.com/31733941/193419307-4a100d8b-405f-4e94-a24b-2433c206ce0f.png)

If you need further input or want to keep this issue alive feel free to reopen it. Yea

**Comment by brnsolikyl** [comment]
I think it's something that many groups would appreciate, for sure! Although the solution I see to this is to add a filter on the history page (general and per place) - "activities only". At least that's where I'd look for it, and it would not clutter the sidenav menu or the activities page
