### ISSUE TITLE
Group Search Improvements

### ISSUE THREAD

**Issue by heytheretyo** [karrot-dev/karrot-frontend#2681]
I'm thinking of adding a filter for certain groups according to their tags or country. If i have the time I could hit a PR, or anyone could do it since its easy to implement.

This is where it could be implemented:

![image](https://github.com/karrot-dev/karrot-frontend/assets/142723158/92a85a50-5c46-4c6e-a8fd-7ba5f0b0da2c)

**Comment by TylerH123** [comment]
Hello, I would like to claim this.

**Comment by heytheretyo** [comment]
Sure! I don't have time to do it so feel free to implement it as you wish.

**Comment by nicksellen** [comment]
Hey, thanks for the idea, and the enthusiasm to implement it.

At the moment groups don't currently have tags, and their country is not recorded (only address as a text field + location lat/lng).

I don't see this as a good started task for that reason.

**Comment by nicksellen** [comment]
Moved to codeberg https://codeberg.org/karrot/karrot-frontend/issues/2681
