### ISSUE TITLE
Push message with activity in title should respect user timezone

### ISSUE THREAD

**Issue by nicksellen** [karrot-dev/karrot-frontend#2682]
This activity is at 9:00 for me, not 10:00

![image](https://github.com/karrot-dev/karrot-frontend/assets/31616/f023e7ac-ac66-4c6f-94b8-2d028d7d2708)

**Comment by shennyj** [comment]
id like to claim this

**Comment by nicksellen** [comment]
Are you a student with a "contribute to an open source project" assignment?

Can you give a brief overview of how you would propose to solve the issue?

I don't have a lot of time to support anyone at the moment, so you'll need to have enough resources to complete this task yourself, do you think you can do that?

**Comment by shennyj** [comment]
We have more than enough resources to be able to complete this task, thank you for letting us contribute!

**Comment by nicksellen** [comment]
Moved to codeberg https://codeberg.org/karrot/karrot-frontend/issues/2682
