### ISSUE TITLE
Feedback is hidden when place status is not co-operating

### ISSUE THREAD

**Issue by dwaxweiler** [karrot-dev/karrot-frontend#2683]
**Steps to reproduce**

1. Create an activity series.
2. Do at least one activity and give feedback.
3. ~Delete the activity series.~ Set the place status to something else than "co-operating".
4. Check the feedback page at that place.

**What happens**

While the total numbers are shown, the message in a green box with the title "No feedback yet" and the text "This page will be filled once more feedback is available" is shown below instead of feedback entries.

**What should happen**

The feedback given should stay visible.

**Comment by nicksellen** [comment]
I just tried to recreate that, and I was able to delete a series, and still see the feedback for that place (I did it here fyi https://dev.karrot.world/#/group/6/place/17/feedback).

However, if I change the place status to something other than active / co-operating, then the feedback does go away, and I can see where it does that in the code.

Could it be that you also changed the status after you deleted the series?

**Comment by nicksellen** [comment]
Tonight I pushed a change with the deployment so that:
- activities listed for the group/place have an explicit "place status = active" filter
- activities listed for feedback, do _not_ specify this filter

So, see if it behaves how you would expect now, otherwise we can follow up. No rush.

**Comment by dwaxweiler** [comment]
@nicksellen, superb! I have updated the issue title and description with the status detail. Another Foodsaver and I confirm that it works now. Thanks!

**Comment by nicksellen** [comment]
Great! ✨
