### ISSUE TITLE
Withdrew statistic column calculates incorrectly

### ISSUE THREAD

**Issue by nicksellen** [karrot-dev/karrot-frontend#2687]
It sums everything as if "missed" and "late" options were set to off, whereas it should follow those settings.

![image](https://github.com/karrot-dev/karrot-frontend/assets/31616/6d41850f-2cad-4c3a-89ca-5ce201b5ee2c) 
![image](https://github.com/karrot-dev/karrot-frontend/assets/31616/83683ae7-7599-40b6-9c8e-01bd9300826b)

**Comment by jameleu** [comment]
is this fixed? I would like to attempt to fix this. is this in the group -> statistics (activity) settings?

are there any pointers to get started?

**Comment by nicksellen** [comment]
Moved to codeberg https://codeberg.org/karrot/karrot-frontend/issues/2687
