### ISSUE TITLE
Unable to set monthly recurring activity

### ISSUE THREAD

**Issue by decentral1se** [karrot-dev/karrot-frontend#2696]
This was the recommended example in the docs below. 2 of the links are dead however.

![image](https://github.com/karrot-dev/karrot-frontend/assets/1991377/f1af90d1-0d0d-4d78-9c8a-5a907c05edb0)

**Comment by nicksellen** [comment]
Ah good to know! I've created monthly ones before, although not with a human text description, but the raw recurrence rule.

https://icalendar.org/rrule-tool.html has a little UI to generate one.

Something that would be nice to implement inside Karrot.

The other thing you might run into is the maximum "weeks in advance" is set per place, and max is 10 (in the UI), which for monthly is only 2.

**Comment by nicksellen** [comment]
I reworked it a bit:
- first link goes to https://icalendar.org/rrule-tool.html
- second two links are replaced with buttons, which insert the mentioned rule into the input box

![image](https://github.com/karrot-dev/karrot-frontend/assets/31616/ac9b792e-1bee-4172-a0f3-8c48e2a07835)

**Comment by decentral1se** [comment]
:heart_decoration:
