### ISSUE TITLE
Unable to create activity

### ISSUE THREAD

**Issue by decentral1se** [karrot-dev/karrot-frontend#2697]
Unsure if I'm doing something wrong?

https://github.com/karrot-dev/karrot-frontend/assets/1991377/8eaa5267-3c18-4370-81cb-649080141e5f

**Comment by nicksellen** [comment]
Ah, you have to create the place first (typing in the box is just for searching already created places).

We should add validation for that situation though. And potentially create a default "General" place you can use for those things.

**Comment by nicksellen** [comment]
I think this is resolved right?

Anyhow, we moved to codeberg! https://codeberg.org/karrot/karrot-frontend/issues/2697
