### ISSUE TITLE
Improve experience of adding Places

### ISSUE THREAD

**Issue by ghost** [karrot-dev/karrot-frontend#2702]
I think this user experience could be improved quite a bit. A lot of this data is probably floating around on various API's like Open Street Maps and I think I saw you mention [Murmurations](https://murmurations.network/), but I don't know what that is about exactly.

I am just opening this issue to start such a discussion!

**Comment by nicksellen** [comment]
We moved to codeberg https://codeberg.org/karrot/karrot-frontend/issues/2702

Although, we don't tend to discuss a lot over on GitHub (as you noticed).
