### ISSUE TITLE
Copy and UX clarification when recieving messages from new groups joined

### ISSUE THREAD

**Issue by sbutler-gh** [karrot-dev/karrot-frontend#2708]
**This has two separate but related UX issues.  Including both, because a solution may be related.**

1. Upon joining a few groups, I had new messages from those groups
<img width="1002" alt="Screen Shot 2024-02-24 at 8 42 05 PM" src="https://github.com/karrot-dev/karrot-frontend/assets/46165064/96c416ee-498e-4795-8c44-f03712534385">

Perhaps there could be more copy on the message preview in the inbox dropdown, to indicate which groups those were messages from?

Potential change:

<img width="1013" alt="Screen Shot 2024-02-24 at 8 55 46 PM" src="https://github.com/karrot-dev/karrot-frontend/assets/46165064/bc5cf2d0-d94c-45e0-9732-29fda1911208">

* * * * *

2. When clicking into the messages, I saw the groups they were from, but then I was missing context about the groups themselves.  I wanted to try and click to view the group, but it wasn't clear to me how.  (Only by seeing the cursor icon on "Application" and clicking there, did I successfully pull up the group page.  People with less technical experience probably won't recognize that.)

<img width="1011" alt="Screen Shot 2024-02-24 at 8 37 25 PM" src="https://github.com/karrot-dev/karrot-frontend/assets/46165064/abd63530-547b-4a02-a931-2db9a3d7c045">

To provide context about the group that you are receiving a message from, after being accepted, I can imagine two approaches:

First, there could be a simple "Go to group" hyperlink provided next to the group name in the message

<img width="1007" alt="Screen Shot 2024-02-24 at 8 37 34 PM" src="https://github.com/karrot-dev/karrot-frontend/assets/46165064/61e9418c-a445-4edf-a47f-a9ac7eb54cf0">

Alternatively, there could also be a section in the message, at the top, that gives the group description as a reminder about context

<img width="1009" alt="Screen Shot 2024-02-24 at 8 52 16 PM" src="https://github.com/karrot-dev/karrot-frontend/assets/46165064/881d3145-538c-4b91-a7c7-85cb4f4bd0f8">

**Comment by nicksellen** [comment]
Maybe a modal dialog to show the group info without losing your context could be useful?

**Comment by sbutler-gh** [comment]
How would you imagine that working?  Not sure if I understand your suggestion completely, though I think adding another UI element could be overboard (also complicated on mobile potentially?).  I would start with something simple that just edits the content in the existing components to make it more clear, and I think I would be okay with that as a solution for the ambiguity I encountered.
