### ISSUE TITLE
Build cordova mobile app for iOS

### ISSUE THREAD

**Issue by nicksellen** [karrot-dev/karrot-frontend#938]
We have macOS enabled in our circleci environment so hopefully can get it built for iOS.

See https://circleci.com/docs/2.0/sample-config/#sample-configuration-with-multiple-executor-types-macos--docker for a guide on how to add macOS build steps to our circleci config.

I tried out adding a step to our circleci config and it worked, you can see the config here https://github.com/yunity/karrot-frontend/blob/ios/.circleci/config.yml#L44-L51. I don't know what to put in there beyond that though.

Another option could be to explore if we can use https://github.com/fastlane/fastlane to help us, seems to integrate with circleci, and have a [cordova plugin](https://github.com/bamlab/fastlane-plugin-cordova). I did not investigate it any further though.

Superbil was interested to investigate :) - what is your github username btw?

**Comment by Superbil** [comment]
I already had an fastlane script for your app, let me see what I can do.

**Comment by Superbil** [comment]
I had make fastlane script to build project, it don't support auto deploy with CI yet.
CI system need special setup to work with personal apple account.

**Comment by nicksellen** [comment]
Is it something you'd be interested to continue working on?

**Comment by tiltec** [comment]
Hey @Superbil, how is it going?

**Comment by Superbil** [comment]
@tiltec Just setup new profile key and try to rebuild it again.

**Comment by brnsolikyl** [comment]
Just leaving it registered here that people from the Bike Kitchen are requesting this app, especially because another one is joining the Karrot group and many there have iphones.

**Comment by tiltec** [comment]
@Superbil what was your experience when you worked on it? Were there some major roadblocks?

**Comment by Superbil** [comment]
@tiltec Build progress must fix some flow about build cordova, build script (fastlane) had some to implement. I think that's all.
When this to feature finish, that should work. I think end of November will finish.

**Comment by dwaxweiler** [comment]
Hello, could we open this issue again please? Several people from my group are requesting an iPhone app. How complex is it to do with the current tech stack? @Superbil any news from your side?

**Comment by brnsolikyl** [comment]
If there's demand, it should definitely be re-opened.

**Comment by dwaxweiler** [comment]
This would still be nice.

**Comment by nicksellen** [comment]
We're a bit stuck without any iOS dev people in our team, so any ideas for that would help a lot!
